[package]
name = "conc_cli"
version = "0.1.0"
edition = "2021"

[lib]
name = "conc"
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
wasm-bindgen = "0.2"
